/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cbooy.beans;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-06-28")
public class Caller implements org.apache.thrift.TBase<Caller, Caller._Fields>, java.io.Serializable, Cloneable, Comparable<Caller> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Caller");

  private static final org.apache.thrift.protocol.TField CALLER_FIELD_DESC = new org.apache.thrift.protocol.TField("caller", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField REQUIRED_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("requiredId", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CallerStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CallerTupleSchemeFactory());
  }

  public String caller; // required
  public String requiredId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CALLER((short)1, "caller"),
    REQUIRED_ID((short)2, "requiredId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CALLER
          return CALLER;
        case 2: // REQUIRED_ID
          return REQUIRED_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.REQUIRED_ID};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CALLER, new org.apache.thrift.meta_data.FieldMetaData("caller", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REQUIRED_ID, new org.apache.thrift.meta_data.FieldMetaData("requiredId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Caller.class, metaDataMap);
  }

  public Caller() {
  }

  public Caller(
    String caller)
  {
    this();
    this.caller = caller;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Caller(Caller other) {
    if (other.isSetCaller()) {
      this.caller = other.caller;
    }
    if (other.isSetRequiredId()) {
      this.requiredId = other.requiredId;
    }
  }

  public Caller deepCopy() {
    return new Caller(this);
  }

  public void clear() {
    this.caller = null;
    this.requiredId = null;
  }

  public String getCaller() {
    return this.caller;
  }

  public Caller setCaller(String caller) {
    this.caller = caller;
    return this;
  }

  public void unsetCaller() {
    this.caller = null;
  }

  /** Returns true if field caller is set (has been assigned a value) and false otherwise */
  public boolean isSetCaller() {
    return this.caller != null;
  }

  public void setCallerIsSet(boolean value) {
    if (!value) {
      this.caller = null;
    }
  }

  public String getRequiredId() {
    return this.requiredId;
  }

  public Caller setRequiredId(String requiredId) {
    this.requiredId = requiredId;
    return this;
  }

  public void unsetRequiredId() {
    this.requiredId = null;
  }

  /** Returns true if field requiredId is set (has been assigned a value) and false otherwise */
  public boolean isSetRequiredId() {
    return this.requiredId != null;
  }

  public void setRequiredIdIsSet(boolean value) {
    if (!value) {
      this.requiredId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CALLER:
      if (value == null) {
        unsetCaller();
      } else {
        setCaller((String)value);
      }
      break;

    case REQUIRED_ID:
      if (value == null) {
        unsetRequiredId();
      } else {
        setRequiredId((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CALLER:
      return getCaller();

    case REQUIRED_ID:
      return getRequiredId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CALLER:
      return isSetCaller();
    case REQUIRED_ID:
      return isSetRequiredId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Caller)
      return this.equals((Caller)that);
    return false;
  }

  public boolean equals(Caller that) {
    if (that == null)
      return false;

    boolean this_present_caller = true && this.isSetCaller();
    boolean that_present_caller = true && that.isSetCaller();
    if (this_present_caller || that_present_caller) {
      if (!(this_present_caller && that_present_caller))
        return false;
      if (!this.caller.equals(that.caller))
        return false;
    }

    boolean this_present_requiredId = true && this.isSetRequiredId();
    boolean that_present_requiredId = true && that.isSetRequiredId();
    if (this_present_requiredId || that_present_requiredId) {
      if (!(this_present_requiredId && that_present_requiredId))
        return false;
      if (!this.requiredId.equals(that.requiredId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_caller = true && (isSetCaller());
    list.add(present_caller);
    if (present_caller)
      list.add(caller);

    boolean present_requiredId = true && (isSetRequiredId());
    list.add(present_requiredId);
    if (present_requiredId)
      list.add(requiredId);

    return list.hashCode();
  }

  public int compareTo(Caller other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCaller()).compareTo(other.isSetCaller());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCaller()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.caller, other.caller);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRequiredId()).compareTo(other.isSetRequiredId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRequiredId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requiredId, other.requiredId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Caller(");
    boolean first = true;

    sb.append("caller:");
    if (this.caller == null) {
      sb.append("null");
    } else {
      sb.append(this.caller);
    }
    first = false;
    if (isSetRequiredId()) {
      if (!first) sb.append(", ");
      sb.append("requiredId:");
      if (this.requiredId == null) {
        sb.append("null");
      } else {
        sb.append(this.requiredId);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    if (caller == null) {
      throw new TProtocolException("Required field 'caller' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CallerStandardSchemeFactory implements SchemeFactory {
    public CallerStandardScheme getScheme() {
      return new CallerStandardScheme();
    }
  }

  private static class CallerStandardScheme extends StandardScheme<Caller> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Caller struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CALLER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.caller = iprot.readString();
              struct.setCallerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // REQUIRED_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.requiredId = iprot.readString();
              struct.setRequiredIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Caller struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.caller != null) {
        oprot.writeFieldBegin(CALLER_FIELD_DESC);
        oprot.writeString(struct.caller);
        oprot.writeFieldEnd();
      }
      if (struct.requiredId != null) {
        if (struct.isSetRequiredId()) {
          oprot.writeFieldBegin(REQUIRED_ID_FIELD_DESC);
          oprot.writeString(struct.requiredId);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CallerTupleSchemeFactory implements SchemeFactory {
    public CallerTupleScheme getScheme() {
      return new CallerTupleScheme();
    }
  }

  private static class CallerTupleScheme extends TupleScheme<Caller> {

    public void write(org.apache.thrift.protocol.TProtocol prot, Caller struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.caller);
      BitSet optionals = new BitSet();
      if (struct.isSetRequiredId()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetRequiredId()) {
        oprot.writeString(struct.requiredId);
      }
    }

    public void read(org.apache.thrift.protocol.TProtocol prot, Caller struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.caller = iprot.readString();
      struct.setCallerIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.requiredId = iprot.readString();
        struct.setRequiredIdIsSet(true);
      }
    }
  }

}

